### ISSUE TITLE
UFuncTypeError: Cannot cast ufunc 'subtract' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

### ISSUE THREAD

**Issue by anil-goudar** [RezaSoleymanifar/DA-SDN#1]
Hello,
 Thanks for your good work. I was working on the same problem and trying to implement the same. But when I am working with own dataset created randomly using numpy, I am getting the above error.

Here is sample data:

```
[[ 1  5]
 [ 1 10]
 [ 1 15]
 [ 1  1]
 [ 1  1]
 [ 1  2]
 [ 1  3]
 [ 1  4]
 [ 2  5]
 [ 2 10]
 [ 2 15]
 [ 2  1]
 [ 2  1]
 [ 2  2]
 [ 2  3]
 [ 2  4]
 [ 3  5]
 [ 3 10]
 [ 3 15]
 [ 3  1]
 [ 3  1]
 [ 3  2]
 [ 3  3]
 [ 3  4]
 [ 4  5]
 [ 4 10]
 [ 4 15]
 [ 4  1]
 [ 4  1]
 [ 4  2]
 [ 4  3]
 [ 4  4]
 [ 5  5]]
```

and I am running the project as

`python3 train.py data.npy 0.1 1 ll`

and I am getting the error as:

```
Traceback (most recent call last):

  File "D:\Desktop\Security\ECP\train.py", line 15, in <module>
    obj = DA(data = data, max_m = int(max_m), gamma = float(gamma), interactive = int(interactive))

  File "D:\Desktop\Security\ECP\DALL.py", line 11, in __init__
    self.x = self.pre_process(data)

  File "D:\Desktop\Security\ECP\DALL.py", line 47, in pre_process
    data -= np.mean(data, axis = 0)

UFuncTypeError: Cannot cast ufunc 'subtract' output from dtype('float64') to dtype('int32') with casting rule 'same_kind
```

Please help me  to resolve the issue.

**Comment by anil-goudar** [comment]
I resolved it by changing the data i was passing.

**Comment by RezaSoleymanifar** [comment]
Dear Anilkumar,

Thank you for your interest in my repo. I’m glad that your issue has resolved. I’m just curious :) Are you working on software defined networks?

Regards,

-----------------------------------------------
REZA SOLEYMANIFAR

Ph.D Student of Industrial Engineering
University of Illinois at Urbana-Champaign
The Grainger College of Engineering
160 Coordinated Science Lab
reza2@illinois.edu

**Comment by anil-goudar** [comment]
Dear RezaSoleymanifar,

 Yes RezaSoleymanifar, I am working on SDN and controller placement problem. I found your repository so helpful. Thank you so much.

**Comment by RezaSoleymanifar** [comment]
Hi!

I’m really happy you found my repo useful. Keep up the good work and contribute to scientific community. 

Regards,

-----------------------------------------------
REZA SOLEYMANIFAR

Ph.D Student of Industrial Engineering
University of Illinois at Urbana-Champaign
The Grainger College of Engineering
160 Coordinated Science Lab
reza2@illinois.edu

**Comment by anil-goudar** [comment]
Thank You very much. I am happy to contribute and you guys are the inspiration to me.
